name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17.5
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}